### ISSUE TITLE
i found an error i need a help to solve 

### ISSUE THREAD

**Issue by heisenberg898** [Zartris/Airsim-terminal-drone-control#1]
ile "D:\airsim\keycontrol\Airsim-terminal-drone-control\simple_control.py", line 317, in <module>
    controller.run()
  File "D:\airsim\keycontrol\Airsim-terminal-drone-control\simple_control.py", line 301, in run
    self.enter_keyboard_control()
  File "D:\airsim\keycontrol\Airsim-terminal-drone-control\simple_control.py", line 238, in enter_keyboard_control
    while kc.thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

this error is bcs of i enter kc 
and i install pykey also

**Comment by tirkarthi** [comment]
This seems like a problem with using it in Python 3.9 . Please try replacing `isAlive` with `is_alive` since it was deprecated and removed in Python 3.9 or try using Python 3.8 .

**Comment by heisenberg898** [comment]
tried with python 3.8
same issue is there

**Comment by Zartris** [comment]
Hi @heisenberg898 
I'm sorry to hear that you cannot make it to work.
I tried using python 3.9, and if I change the thread.isAlive() to thread.is_alive() it works without a problem.
Can you tell me what idea you are using (if any) and what operating system you are on?
