### ISSUE TITLE
KeyController.py automatically deleted by windows

### ISSUE THREAD

**Issue by belongtothenight** [Zartris/Airsim-terminal-drone-control#3]
Just to inform you this issue, when I download your code, the "KeyController.py" is automatically deleted by windows system, even if I manually create another one and paste the code from your repository, it will be deleted again. Seems like it's been regarded as virus.

Environment:
- windows 11
- python 3.9
- unreal engine 4

**Comment by Zartris** [comment]
Hmmm, that seems like a problem indeed.
I do not have windows 11 installed, but my theory is that it might be the library that records key presses that make windows act up.
I can assure you there is no malice intended in the program.
Thanks for bringing it to my attention.

**Comment by Zartris** [comment]
Are you using pyinstaller? or is it finding the .py files as viruses?
Maybe you can describe to me how I can replicate the problem :)

**Comment by belongtothenight** [comment]
Well, that was a really fast reply!
I was looking for sample codes on how to interact with AirSim API and found what you coded, so there is no pressure on any changes in your code. (I did notice that your code works on Linux machines)

I'm not using pyinstaller, and the picture below is the packages I use (same as what I installed using cmd). I've never encountered anything like this before and found out about this after the windows defender triggered.
![image](https://user-images.githubusercontent.com/106849935/172039489-28c0397d-657c-46ef-839c-1223f45e644f.png)

So after I download your code as a ZIP file, extract it, and open it with PyCharm (I didn't install the "threading" package). A few seconds later, "KeyController,py" suddenly disappears. I thought it was a bug and created an empty Python file, but it still disappears a few seconds later after pasting your code inside.

Again, no pressure to fix it; I can still view your code on Github. Thanks for open source your code!

**Comment by Zartris** [comment]
I did some digging and found a similar problem https://stackoverflow.com/questions/71350676/why-does-when-i-import-pynput-and-use-it-it-deletes-my-python-file

It is pynput windows 11 problems.
Now it is just a matter of trying to find the fix.

**Comment by Zartris** [comment]
It's not just a problem on window 11, I can recreate on windows 10. 
It seems that windows defender decided to not allow pynput anymore.

**Comment by Zartris** [comment]
I have updated the master branch with a solution that at least works for windows 10 as it is right now.
Can I get you to test it out on windows 11 and report back if it gives you further problems?

**Comment by belongtothenight** [comment]
Yes, and your fix is working. Windows defender has not triggered anymore.
I'm able to run "KeyController.py", but struggle to run the commands. Since once I run it, I can't type commands like "arm", or "kc".
![image](https://user-images.githubusercontent.com/106849935/172045889-5c96ced1-8a45-4e84-9880-9e5f1fd55958.png)

**Comment by Zartris** [comment]
That's great! The reason why you cannot use any commands is that you have to run simple_control.py as it uses the key controller :)

**Comment by belongtothenight** [comment]
Thank you, the w/a/s/d works nicely!
