### ISSUE TITLE
Keyboard q, e, z, x

### ISSUE THREAD

**Issue by twoimo** [Zartris/Airsim-terminal-drone-control#4]
It's not working.

**Comment by Zartris** [comment]
How is it not working?
Can you tell me a bit more? 
What is your is, what is the AirSim version, what is the python version.

**Comment by Zartris** [comment]
Pushed an update to fix this problem.
If you pull the master branch it should be working nicely again.

**Comment by ferper04** [comment]
not working

**Comment by ferper04** [comment]
current pos:
 x:0.0, y:0.0
 z:0.0

current vel:
 vx:6.403933981964414e-43, nvx:0.0
 vy:3572346880.0, nvy:20.0
 vz:1.821688003622262e-43, nvz:0

current pos:
 x:0.0, y:0.0
 z:0.0

current vel:
 vx:6.403933981964414e-43, nvx:0.0
 vy:9457696768.0, nvy:20.0
 vz:1.821688003622262e-43, nvz:0

current pos:
 x:0.0, y:0.0
 z:0.0

current vel:
 vx:6.403933981964414e-43, nvx:0.0
 vy:9457696768.0, nvy:20.0
 vz:1.821688003622262e-43, nvz:0
